### ISSUE TITLE
Issue with .large navigation bar titles

### ISSUE THREAD

**Issue by whitetown** [siteline/SwiftUIRefresh#1]
Unfortunately, it does not work properly with .large titles if I try to scroll: 
Large Title does not collapse

    @State var items = [String] = ["a", "b"]
    @State var isRefresing  = false

    var body: some View {

        NavigationView {
            List(self.items, id: \.self) {
                Text($0)
            }
            .background(PullToRefresh(action: {
                self.reloadData()
            }, isShowing: self.$isRefresing))

            .navigationBarTitle(Text("Title"), displayMode: .large)
        }
   }

**Comment by consolelogluke** [comment]
Same issue here.

**Comment by ldiqual** [comment]
Sorry for the delay, for some reason I didn't get a notification for this issue. This is related to https://github.com/timbersoftware/SwiftUI-Introspect/issues/2 and I believe this is a SwiftUI bug where `.background()` messes with large titles. I'll need to update the code so that we support introspecting the view hierarchy by using `.overlay()` instead of `.background()`. Will let you know when that's out.
